type PlanetPart = string[];

// p: purple, e: earth-green, o: ocean-blue, m: mars-red, d: desert, w: white, i: ice-blue
// c: crater-grey, I: ring-grey, S: light-ring-grey
// q: lava, j: city-lights
// g: green (for moons/continents)
// Uppercase letters are darker shades

export const PLANET_BASES: PlanetPart[] = [
    // 1. Earth-like
    [
        '   oOoooOo   ',
        ' oOeeEeeEeOo ',
        'oOeeEeeeeeeEo',
        'oOeeeeeeEoOoo',
        'oeeeeeeooOoOo',
        'OeeeeoooooOOo',
        'oOeeEeoOooooo',
        'oOooooooOoooo',
        'oOeeeeeeEoOoo',
        'oOeeEeeeeeeEo',
        ' oOeeEeeEeOo ',
        '   oOoooOo   ',
    ],
    // 2. Mars-like
    [
        '   mmMmmMm   ',
        ' mMmwwMwMmMm ',
        'mMmwwwwwwMmMm',
        'mMwwwwcwwwMmM',
        'mwwCccwwwwwwm',
        'MwCccwwwwwwwM',
        'mwwwwwwwwwwCm',
        'MwwwwwwwwwwCM',
        'mMwwwwwwwwMmM',
        'mMmwwwwwwMmMm',
        ' mMmwwMwMmMm ',
        '   mmMmmMm   ',
    ],
    // 3. Gas Giant (Purple)
    [
        '   pPpPpPp   ',
        ' pPpwPwwPpPp ',
        'pPpwwPwwpPpPp',
        'pPwwwPwwwppPp',
        'PwwwPwwwwwwPp',
        'pwwPwPwwwwwPp',
        'PwwwPwwwwwwPp',
        'pwwwPwwwwwwPp',
        'pPwwwPwwwppPp',
        'pPpwwPwwpPpPp',
        ' pPpwPwwPpPp ',
        '   pPpPpPp   ',
    ],
    // 4. Desert Planet
    [
        '   dDdDdDd   ',
        ' dDddDddDddD ',
        'dDddDddDddDdd',
        'dDddDCCdDddDd',
        'DddDcCcdDddDD',
        'dDddDddDddDdd',
        'DddDddDddDddD',
        'dDddDddDddDdd',
        'dDddDccDddDdd',
        'dDddDCCdDddDd',
        ' dDddDddDddD ',
        '   dDdDdDd   ',
    ],
    // 5. Ice Planet
    [
        '   iIiIiIi   ',
        ' iIiiIiiIiiI ',
        'iIiiIiiIiiIii',
        'iIiiIwwIiiIii',
        'IiiIwwwwIiiI ',
        'iIwwwwwwIiiI ',
        'IiiIwwwwIiiI ',
        'iIiiIwwIiiIii',
        'iIiiIiiIiiIii',
        'iIiiIiiIiiIii',
        ' iIiiIiiIiiI ',
        '   iIiIiIi   ',
    ],
    // 6. Molten Planet
    [
        '   mQmQmQm   ',
        ' mQmqQmqMmMm ',
        'mQmqqQmqmQmqM',
        'mMmqqqqqmMmMm',
        'MmMqqQqqmMmMM',
        'mMmqqQqqmMMMm',
        'MmMmqqQmMmMM ',
        'mMmMmqmqMmMmM',
        'mMmMmMMMmMmMm',
        'mMmMmMMMmMmMm',
        ' mMmMmMMMmMm ',
        '   mmMmmMm   ',
    ],
    // 7. Jungle Planet
    [
        '   ggGggGg   ',
        ' gGeeEeeEgGg ',
        'gGeEeeEeeeEgG',
        'gEeeeeeeeEoOg',
        'geeeeeeooOoOg',
        'GeeeeoooooOOg',
        'gGedDeoOooooo',
        'gGooooooOoooo',
        'gGeeeeeeEoOog',
        'gGeEeeeeeeeEg',
        ' gGeeEeeEgGg ',
        '   ggGggGg   ',
    ],
    // 8. Water World
    [
        '   ooOwwOo   ',
        ' oOoooooOoOo ',
        'oOooooOooooOo',
        'oOoooooeoOooo',
        'ooooooooeoooo',
        'Ooooooooooooo',
        'oOoooOooooooo',
        'oOoooooooOooo',
        'oOooeeeooOooo',
        'oOooooOooooOo',
        ' oOoooooOoOo ',
        '   ooOwwOo   ',
    ],
    // 9. Crystal Geode
    [
        '   CCpPpCC   ',
        ' CCpPpipPpCC ',
        'CCpPpiiipPpCC',
        'CpPpiiiwiPpC ',
        'CpPpiiwwwippC',
        'CPpiwwwwippPC',
        'CpPpiiwwwippC',
        'CpPpiiiwiPpC ',
        'CCpPpiiipPpCC',
        ' CCpPpipPpCC ',
        '   CCpPpCC   ',
    ],
    // 10. Night City
    [
        '   CCCjJCC   ',
        ' CCjJjJjJjCC ',
        'CCjJjCjCjJjCC',
        'CCjCjJjJjCjCC',
        'CjCjJjCjJjCjC',
        'CjJjCjJjCjJjC',
        'CjCjJjCjJjCjC',
        'CCjCjJjJjCjCC',
        'CCjJjCjCjJjCC',
        ' CCjJjJjJjCC ',
        '   CCCjJCC   ',
    ],
    // 11. Toxic World
    [
        '   gGgLgGg   ',
        ' gGgLlLgGgLg ',
        'gGgLllllLgGgL',
        'gLgllLlllgLlg',
        'LgllLlllLllgL',
        'gLllLllllLlgL',
        'LgllLlllLllgL',
        'gLglllLlllgLg',
        'gGgLllllLgGgL',
        'gGgLlLgGgLgGg',
        ' gGgLgGgLgLg ',
        '   gGgGgGg   ',
    ],
    // 12. Striped Gas Giant (Jupiter-like)
    [
        '   dDdwwDd   ',
        ' dDwwwwwwDdd ',
        'dDwwwwwwwwDdd',
        'dDddDddDddDdd',
        'Ddd898898ddDD',
        'dD89889889Ddd',
        'Ddd898898ddDD',
        'dDddDddDddDdd',
        'dDwwwwwwwwDdd',
        'dDwwwwwwDddDd',
        ' dDwwwwwwDdd ',
        '   dDdwwDd   ',
    ],
    // 13. Metallic Planet
    [
        '   cCcwCcC   ',
        ' cCcwwwwCcCc ',
        'cCcwwwwwwCcCc',
        'cwwwwwwwwwwCc',
        'cwwwwcwcwwwwc',
        'CwwwcwcwwwwwC',
        'cwwwwcwcwwwwc',
        'cwwwwwwwwwwCc',
        'cCcwwwwwwCcCc',
        'cCcwwwwCcCcCc',
        ' cCcwCcCcCc ',
        '   cCcCcCc   ',
    ],
    // 14. Tectonic Cracked World
    [
        '   dDdDdDd   ',
        ' dDdqQqqDddD ',
        'dDdqqQqqqDddD',
        'dDqqqQqqqqdDd',
        'DqqqqQqqqqqDD',
        'dqqqqqQqqqqdd',
        'DqqqqQqqqqqDD',
        'dDqqqQqqqqdDd',
        'dDdqqQqqqDddD',
        'dDdqQqqDddDdd',
        ' dDdqQdDddD ',
        '   dDdDdDd   ',
    ],
    // 15. Teal/Green Gas Giant
    [
        '   eEgGgEe   ',
        ' eEgGwGwgEeE ',
        'eEgwwGwwgEeEg',
        'eEwwwGwwwggEg',
        'EwwwGwwwwwwEg',
        'ewwGwGwwwwwEg',
        'EwwwGwwwwwwEg',
        'ewwwGwwwwwwEg',
        'eEwwwGwwwggEg',
        'eEgwwGwwgEeEg',
        ' eEgGwGwgEeE ',
        '   eEgGgEe   ',
    ]
];

export const PLANET_DETAILS: PlanetPart[] = [
    // 1. No Details
    [' '],
    // 2. Large Green Continent
    [
        '             ',
        '   ggGg      ',
        '  gGeeeGg    ',
        ' gGeeeeeeGg  ',
        ' gGeeeeeeGg  ',
        '  gGeeeeGg   ',
        '   ggGgGg    ',
        '     gg      ',
        '             ',
    ],
    // 3. Island Chain
    [
        '             ',
        '     gG      ',
        '  g        gG',
        ' Gg   g      ',
        '     Gg      ',
        '  gG         ',
        '        gGg  ',
        '             ',
        '             ',
    ],
    // 4. Giant Crater
    [
        '             ',
        '    cCc      ',
        '  cCcccCc    ',
        ' cCcccccCc   ',
        ' cCcccCcCc   ',
        '  cCcCcCc    ',
        '    ccc      ',
        '             ',
        '             ',
    ],
    // 5. Many Small Craters
    [
        '             ',
        '   cc   c    ',
        ' c   cC      ',
        '      c   cC ',
        ' cc  c       ',
        'c    cC  cc  ',
        '       c     ',
        '  cC     c   ',
        '             ',
    ],
    // 6. Great Red Spot
    [
        '             ',
        '             ',
        '             ',
        '   mmM       ',
        '  mMMMmMm    ',
        ' mMMMMwMmM   ',
        '  mMMMMmM    ',
        '   mmMmm     ',
        '             ',
    ],
    // 7. Polar Ice Caps
    [
        '   iIiiIiI   ',
        ' iIwwwwwwwIi ',
        'iIwwwwwwwwwIi',
        '             ',
        '             ',
        '             ',
        '             ',
        '             ',
        'iIwwwwwwwwwIi',
        ' iIwwwwwwwIi ',
        '   iIiiIiI   ',
    ],
    // 8. Glowing Fissures
    [
        '             ',
        '     qQ      ',
        ' q  qQqq     ',
        ' Qq qQqqq q  ',
        ' qqqqQqqq Qq ',
        '  qqqQqqqqq  ',
        '   qQqqqQqq  ',
        '    qQ  Qq   ',
        '             ',
    ],
    // 9. City Lights
    [
        '             ',
        '      jJ     ',
        '   jJj       ',
        '  jJj j j    ',
        ' j jJj jJj j ',
        '    j jJj jJj',
        '       j jJj ',
        '     jJ      ',
        '             ',
    ],
    // 10. Erupting Volcano
    [
        '      q      ',
        '     qQ      ',
        '    qQq      ',
        '   cCcCc     ',
        '  cCCCCCc    ',
        ' cCCmMMCCc   ',
        'cCCmMMMMCCc  ',
        '             ',
        '             ',
    ],
    // 11. Geometric Anomaly
    [
        '    pPp      ',
        '   pP P      ',
        '  pP p       ',
        ' pP  p       ',
        'pP p pPp     ',
        ' pP p p p p  ',
        '  pPp p p p  ',
        '     pPp p   ',
        '        pPp  ',
    ],
    // 12. Swirling Clouds
    [
        '   ww        ',
        '  w  ww w    ',
        ' w w w www   ',
        '  www www w  ',
        '   w www ww  ',
        '  w www w w  ',
        ' w www   w   ',
        '  w w w w    ',
        '   w   w     ',
    ],
    // 13. River Delta
    [
        '      o      ',
        '     oOo     ',
        '    oO O o   ',
        '   oO  o  O  ',
        '  oO  oOo  o ',
        ' oO ooO OooO ',
        'oO o O o O O ',
        ' O  o   o    ',
        '             ',
    ],
    // 14. Dense Forests
    [
        '   ggGg      ',
        '  gGgggGg    ',
        ' gGggggggGg  ',
        ' gGggggggGg  ',
        '  gGggggGg   ',
        '   ggGgGg    ',
        '     gg      ',
        '             ',
        '             ',
    ],
    // 15. Mountain Range
    [
        '      C      ',
        '     cCc     ',
        '    cwcwc    ',
        '   cwcwcwc   ',
        '  cwcwcwcwc  ',
        ' cwcwcwcwcwc ',
        'cwcwcwcwcwcwc',
        '             ',
        '             ',
    ],
];

export const PLANET_RINGS: PlanetPart[] = [
    // 1. No Rings
    [' '],
    // 2. Thin Horizontal
    [
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '   ISSSSSSSSSSSSSSI   ',
        '    ISSSSSSSSSSSI     ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
    ],
    // 3. Thick Saturn-like
    [
        '                        ',
        '                        ',
        '                        ',
        '  ISSSSSIIISSSSSSSI   ',
        '   ISSSSSSSSSSSSSSI   ',
        '    ISSSSSSSSSSSI     ',
        '     ISSIISSSSI       ',
        '                        ',
        '                        ',
        '                        ',
    ],
    // 4. Thin Tilted
    [
        '                        ',
        '             II         ',
        '           ISSI         ',
        '          ISSSI         ',
        '         ISSSSI         ',
        '        ISSSSSI         ',
        '       ISSSSSSI         ',
        '      ISSSSSSI          ',
        '     ISSSSSI            ',
        '    ISSSSI              ',
        '   ISSI                 ',
        '  II                    ',
    ],
    // 5. Thick Tilted
    [
        '                        ',
        '             IIII       ',
        '           ISSSSI       ',
        '         IISSSSSII      ',
        '       IISSSSSSSSII     ',
        '      IISSSSSSSSSSII    ',
        '     IISSSSSSSSSSSII    ',
        '    IISSSSSSSSSSSII     ',
        '   IISSSSSSSSSSII       ',
        '  IISSSSSSSSII          ',
        ' ISSSSSI                ',
        'IIII                    ',
    ],
    // 6. Double Rings
    [
        '                        ',
        '                        ',
        '   ISSIISSIISSIISSI   ',
        '    ISSSSSSSSSSSI     ',
        '                        ',
        '   ISSSSSSSSSSSSSSI   ',
        '    ISSIISSIISSI      ',
        '                        ',
        '                        ',
        '                        ',
    ],
    // 7. Debris Field Ring
    [
        '                        ',
        '                        ',
        '  I S I S S II S SI S ',
        '   S I S I S S I S I  ',
        '    I S I S S II S SI   ',
        '   S I S I S S I S I    ',
        '  I S I S S II S SI S   ',
        '                        ',
        '                        ',
        '                        ',
    ],
    // 8. Vertical Ring
    [
        '           II           ',
        '          ISSI          ',
        '         ISSSSI         ',
        '        ISSSSSSI        ',
        '       ISSSSSSSI        ',
        '       ISSSSSSSI        ',
        '       ISSSSSSSI        ',
        '        ISSSSSSI        ',
        '         ISSSSI         ',
        '          ISSI          ',
        '           II           ',
    ],
    // 9. Faint Ethereal Ring
    [
        '                        ',
        '                        ',
        '                        ',
        '   c c c c c c c c c c c',
        '    c c c c c c c c c c ',
        '   c c c c c c c c c c c',
        '    c c c c c c c c c c ',
        '                        ',
        '                        ',
        '                        ',
    ],
    // 10. Close Inner Ring
    [
        '                        ',
        '                        ',
        '                        ',
        '                        ',
        '        ISSI        ',
        '       ISSSSI       ',
        '        ISSI        ',
        '                        ',
        '                        ',
        '                        ',
    ],
    // 11. Complex Multi-layer
    [
        '                        ',
        '             IIII       ',
        '   ISSI    ISSSSI       ',
        '       IISSSSSSSII      ',
        '      IISSSSSSSSSSII    ',
        '     IISSSSSSSSSSSII    ',
        '    IISSSSSSSSSSII      ',
        '   IISSSSSSSSII         ',
        '  ISSSSI   ISSI         ',
        ' IIII                   ',
        '                        ',
    ],
    // 12. Broken C-Ring
    [
        '                        ',
        '                        ',
        '    ISSSSSSSSSSSI     ',
        '   ISSSSSSSSSSSSSSI   ',
        '  ISSSSS              ',
        ' IISSSI               ',
        '  ISSS                ',
        '   ISSSSSSSSSSSSSSI   ',
        '    ISSSSSSSSSSSI     ',
        '                        ',
    ],
    // 13. Crystalline Ice Ring
    [
        '                        ',
        '                        ',
        '                        ',
        '  iwwiiwwwiiwwwiiwwi  ',
        '   iwwiiwwwiiwwwii    ',
        '    iwwiiwwwiiwwi     ',
        '     iwwiiwwwii       ',
        '                        ',
        '                        ',
        '                        ',
    ],
    // 14. Dark Dusty Ring
    [
        '                        ',
        '                        ',
        '                        ',
        '   CCCCCCICCCCCCCCI   ',
        '    CCCCCCCCCCCCCI    ',
        '     CCCCCCCCCI       ',
        '                        ',
        '                        ',
        '                        ',
        '                        ',
    ],
    // 15. Wide, Thin Ring
    [
        '                        ',
        '                        ',
        '                        ',
        'ISSSSSSSSSSSSSSSSSSSSSSS',
        ' ISSSSSSSSSSSSSSSSSSSSI ',
        '  ISSSSSSSSSSSSSSSSSI   ',
        '   ISSSSSSSSSSSSSSI     ',
        '                        ',
        '                        ',
        '                        ',
    ],
];

export const PLANET_MOONS: PlanetPart[] = [
    // 1. No Moons
    [' '],
    // 2. Single Small Grey Moon
    [
        '      cC               ',
        '     cCCc              ',
        '      cC               ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
    ],
    // 3. Single Large Grey Moon
    [
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '               cCc     ',
        '              cCwcC    ',
        '             cCCCCCc   ',
        '              cCCCc    ',
        '               ccc     ',
    ],
    // 4. Two Small Moons
    [
        '   cC                  ',
        '  cCCc                 ',
        '   cC                  ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                  cC   ',
        '                 cCCc  ',
        '                  cC   ',
    ],
    // 5. Moon with a Moonlet
    [
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '               cCc     ',
        '        iIi   cCwcC    ',
        '             cCCCCCc   ',
        '              cCCCc    ',
        '               ccc     ',
    ],
    // 6. Captured Asteroid
    [
        '                       ',
        '  cC C c  C            ',
        ' C cC cC               ',
        'c c C c                ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
    ],
    // 7. Volcanic Moon
    [
        '                       ',
        '                       ',
        '             mQm       ',
        '            mQQQm      ',
        '           mqqqQqm     ',
        '            mQQQm      ',
        '             mQm       ',
        '                       ',
    ],
    // 8. Ice Moon
    [
        '   iIi                 ',
        '  iIwiI                ',
        ' iIwwwIi               ',
        '  iIwiI                ',
        '   iIi                 ',
        '                       ',
        '                       ',
        '                       ',
    ],
    // 9. Green Habitable Moon
    [
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                 eGe   ',
        '                eGEGe  ',
        '               eGEGEGe ',
        '                eGEGe  ',
        '                 eGe   ',
    ],
    // 10. A Ringed Moon
    [
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '      ISSI             ',
        '     IdDdi             ',
        '      ISSI             ',
        '                       ',
        '                       ',
    ],
    // 11. Moon in Foreground
    [
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        ' cC C c  C             ',
        'C cC cC                ',
        'c c C c                ',
    ],
    // 12. Three Moons in a Line
    [
        '  cC   cC   cC         ',
        ' cCCc cCCc cCCc        ',
        '  cC   cC   cC         ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
    ],
    // 13. Shattered Moon
    [
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '               c   C   ',
        '             C  c      ',
        '              C c      ',
        '            c   C      ',
        '                       ',
    ],
    // 14. Binary Moon System
    [
        '                       ',
        '                       ',
        '             cC  iIi   ',
        '            cCCciIwiI  ',
        '             cC  iIi   ',
        '                       ',
        '                       ',
        '                       ',
    ],
    // 15. Distant Tiny Moon
    [
        '                       ',
        '     w                 ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
        '                       ',
    ],
];
